/** Small original synthesized arcade soundscape. No downloads, recordings or samples. */
export class SoundDeck {
 constructor(){this.ctx=null;this.enabled=true;this.last={};}
 unlock(){if(!this.enabled)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!this.ctx&&A)this.ctx=new A();if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});}catch{this.enabled=false;}}
 tone({frequency=400,end=100,seconds=.12,gain=.045,type='square',delay=0}={}){if(!this.ctx||!this.enabled)return;try{const c=this.ctx,now=c.currentTime+delay;let o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(30,frequency),now);o.frequency.exponentialRampToValueAtTime(Math.max(30,end),now+seconds);g.gain.setValueAtTime(Math.max(0,gain),now);g.gain.exponentialRampToValueAtTime(.0001,now+seconds);o.connect(g).connect(c.destination);o.start(now);o.stop(now+seconds+.012);}catch{}}
 noise({seconds=.23,gain=.12,cutoff=1700}={}){if(!this.ctx||!this.enabled)return;try{const c=this.ctx,rate=c.sampleRate;const buff=c.createBuffer(1,Math.floor(rate*seconds),rate),data=buff.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/data.length;data[i]=(Math.random()*2-1)*(1-t)**1.5;}const source=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();filter.type='lowpass';filter.frequency.value=cutoff;g.gain.value=gain;source.buffer=buff;source.connect(filter).connect(g).connect(c.destination);source.start();source.stop(c.currentTime+seconds);}catch{}}
 play(event){if(!this.enabled)return;const type=event.type;const now=performance.now();if(type==='shoot'){if(now-(this.last.shoot||0)<55)return;this.last.shoot=now;this.tone({frequency:event.heavy?130:310,end:event.heavy?45:90,seconds:event.heavy?.105:.07,gain:event.heavy?.055:.026,type:'sawtooth'});}else if(type==='hit'){if(now-(this.last.hit||0)<70)return;this.last.hit=now;this.tone({frequency:200,end:100,seconds:.08,gain:.03});}else if(type==='kill'){this.noise({seconds:.14,gain:.038,cutoff:1200});this.tone({frequency:165,end:50,seconds:.14,gain:.042});}else if(type==='explosion'){this.noise({seconds:.55,gain:.22,cutoff:800});this.tone({frequency:75,end:30,seconds:.4,gain:.08,type:'sawtooth'});}else if(type==='mount'){
    this.tone({frequency:180,end:470,seconds:.30,gain:.06,type:'sawtooth'});
    this.tone({frequency:620,end:820,seconds:.22,gain:.026,type:'triangle',delay:.11});
  }else if(type==='dismount'){this.tone({frequency:430,end:160,seconds:.17,gain:.035,type:'triangle'});
  }else if(type==='cannon'){this.noise({seconds:.22,gain:.095,cutoff:500});this.tone({frequency:105,end:40,seconds:.28,gain:.075,type:'sawtooth'});
  }else if(type==='vehiclehit'||type==='vehiclelost'){
    this.noise({seconds:.35,gain:.11,cutoff:560});this.tone({frequency:210,end:70,seconds:.25,gain:.052,type:'square'});
  }else if(type==='laser'){this.tone({frequency:690,end:120,seconds:.43,gain:.08,type:'sawtooth'});this.noise({seconds:.33,gain:.035,cutoff:2300});
  }else if(type==='intercept'){this.noise({seconds:.15,gain:.07,cutoff:1350});
  }else if(type==='gateopen'){this.noise({seconds:.35,gain:.09,cutoff:750});this.tone({frequency:240,end:95,seconds:.32,gain:.05,type:'sawtooth'});
  }else if(type==='jump'){this.tone({frequency:220,end:340,seconds:.1,gain:.012,type:'triangle'});}else if(type==='pickup'){this.tone({frequency:470,end:740,seconds:.13,gain:.04,type:'sine'});this.tone({frequency:720,end:1000,seconds:.16,gain:.025,type:'sine',delay:.09});}else if(type==='hurt'||type==='curse'){this.tone({frequency:165,end:38,seconds:.35,gain:.07,type:'sawtooth'});}else if(type==='boss'){this.tone({frequency:130,end:58,seconds:.85,gain:.075,type:'sawtooth'});}else if(type==='warning'){this.tone({frequency:800,end:430,seconds:.2,gain:.025});}else if(type==='won'){[392,523,659,784].forEach((n,i)=>this.tone({frequency:n,end:n,seconds:.35,gain:.06,type:'triangle',delay:i*.15}));}else if(type==='lost'){[300,220,170,100].forEach((n,i)=>this.tone({frequency:n,end:n*.8,seconds:.35,gain:.038,type:'sawtooth',delay:i*.15}));}}
 setEnabled(value){this.enabled=!!value;if(this.enabled)this.unlock();return this.enabled;}
}
